from accounts.api.V1.views.ChangePassword import ChangePasswordView
from accounts.api.V1.views.ObtainAuthToken import CustomeObtainAuthToken
from accounts.api.V1.views.CustomeJWT import Customejwtview
from accounts.api.V1.views.DestroyAuthToken import DestroyAuthToken
from accounts.api.V1.views.IsVerified import IsVerifiedView
from accounts.api.V1.views.Registration import RegistrationView
from accounts.api.V1.views.ResendSMS import ResendSMSView
from accounts.api.V1.views.ResetPasswordSMS import ResetPasswordSMSView
from accounts.api.V1.views.ResetPassword import ResetPasswordView